# Site settings
title: "SeongKu Kang"
description: "Personal page of SeongKu Kang"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "SeongKu Kang"
resume_title:                   "Research Interest"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "seongku@postech.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"


resume_header_intro:  "My principal research interest lies in developing machine learning approaches for effective and efficient information retrieval (IR) systems. These systems have been broadly adopted in many web services, providing curation of web pages, news, and items for millions of people. <br> <i>Effectiveness</i> and <i>efficiency</i> are key requirements of IR systems, i.e., the systems should provide accurate predictions with fast inference time. Naturally, those are two of my main research objectives. <br><b>&bull; Effectiveness of IR Systems</b>. We identified sparsity and ambiguity issues of user feedback, and increased the accuracy by tackling the issues with a broad perspective; this includes utilizing additional data sources [C1, C2, C7], discovering the best query items to elicit preferences [C4], mining underlying patterns from anonymized user feedback [C8], and developing a new learning framework robust to false-negative data [C9]. <br><b>&bull; Efficiency of IR Systems</b>. We focused on applying knowledge distillation, which is a kind of model compression strategy, to IR systems, and our approaches significantly reduced the inference costs; this includes distilling ranking information from the predictions [C5], mining knowledge from models having different capacities [C6], and developing a new distillation approach that utilizes topology built upon the relations in the representation space [C10]."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/SeongKu-Kang"
  resume_twitter_url:           false
  resume_dribbble_url:          false
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          false
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://scholar.google.com/citations?user=fB0K-fMAAAAJ&hl=en"
  resume_medium_url:            false
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
